format = """
[ ](bright-white)\
[󰣇 ](bold fg:black bg:bright-white)\
[](bg:purple fg:bright-white)\
$python\
$rust\
[](fg:purple bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$directory\
[](fg:blue)\
$fill\
[](fg:red)\
$username\
[ ](fg:yellow bg:red)\
$hostname\
[](fg:bright-white bg:yellow)\
$time\
[ ](fg:bright-white)\
\n$character"""

[fill]
symbol = '-'
style = 'fg:bright-black'

[python]
style = "bold fg:black bg:purple"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
pyenv_version_name = false

[rust]
style = "bold fg:black bg:purple"
symbol = ' 󱘗 '
format = '[$symbol($version )]($style)'


[character]
success_symbol = '[  ](bold green)'
error_symbol = '[  ](bold red)'

[directory]
style = "bold fg:black bg:blue"
format = "[$path]($style)"
truncation_length = 5
truncation_symbol = "󰉒 /"
home_symbol = "  "
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bold bg:green"
format = '[[ $symbol $branch](bold fg:black bg:green)]($style)'

[git_status]
style = "bold bg:green"
format = '[[($all_status$ahead_behind) ](bold fg:black bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time](bold fg:black bg:bright-white)]($style)'

[hostname]
ssh_only = true
format = '[󰌘 ](bold fg:black bg:yellow)[$ssh_symbol](bold fg:black bg:yellow)'
trim_at = ''
disabled = false

[username]
style_user = "bold bg:red fg:black"
format = '[ ]($style)[$user]($style)'
disabled = false
show_always = true
