format = """\
$time\
$directory\
$character\
"""

add_newline = false

[directory]
style = "fg:white"
format = "[ $path]($style)"
truncation_length = 5
truncate_to_repo = false

[time]
disabled = false
time_format = "[%R]"
style = "fg:white"
format = '[[$time](fg:bright-black)]($style)'

[character]
success_symbol = '[ |>](bold green)'
error_symbol = '[ |>](bold red)'
