format = """\
$nix_shell\
$directory\
$git_branch\
\n$time\
$character\
"""
add_newline = false

[directory]
style = "fg:white"
format = " [$path]($style)"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "󰉒 "

[time]
disabled = false
time_format = " [%R]"
style = "fg:white"
format = '[$time](fg:bright-black)($style)'

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'

[git_branch]
symbol = " "
style = "bg:green"
format = '[[$symbol $branch](fg:green)]($style)'

[nix_shell]
symbol = '  '
format = '[$symbol]($style)'
